In [1]:
import numpy as np

In [2]:
#np.somefunctionname()

In [3]:
simple = np.arange(1, 25)

In [4]:
simple

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [5]:
arr55 = np.arange(5, 5)
arr55

array([], dtype=int64)

In [6]:
arr55 = np.arange(1, 26).reshape(5, 5)

In [7]:
arr55

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
## Reshape 'simple' array that holds 24 elements

In [9]:
arr122 = simple.reshape(2, 12)
arr122

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [10]:
arr83 = simple.reshape(3, 8)
arr83

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
arr64 = simple.reshape(4, 6)
arr64

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [12]:
arr46 = simple.reshape(6, 4)

In [13]:
arr46

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
arr64

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [15]:
arr64.size

24

In [16]:
arr46.size

24

In [17]:
arr83.size

24

In [18]:
arr64.shape

(4, 6)

In [19]:
arr83.shape

(3, 8)

In [20]:
arr83.shape = (6, 4)

In [21]:
arr83

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

### Addressing elements of an array

In [22]:
arr83

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [23]:
## Element with the value 10

In [24]:
arr83[2, 3]

12

In [25]:
## The first index (axis=0) is for rows, the second index (axis=1) is for columns

In [26]:
arr83[2, 1]

10

In [27]:
## The very first and the very last elements of the array

In [28]:
arr83[0, 0]

1

In [29]:
arr83[5, 3]

24

In [30]:
## Alternative way to output the LAST element

In [31]:
arr83[-1]

array([21, 22, 23, 24])

In [32]:
## This is the last ROW
## When using ONLY ONE axis, you get the full slice for the second one

In [33]:
arr83[-1, -1]

24

In [34]:
### Using slices

In [35]:
arr83[::, -1]

array([ 4,  8, 12, 16, 20, 24])

In [36]:
arr83[-1]

array([21, 22, 23, 24])

In [37]:
## If you give only ONE axis, it is considered to be AXIS 0

In [38]:
arr83[::, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [39]:
arr83

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [40]:
## The above slice prints out all ROWS, and COLUMNS except for the first and the last

In [41]:
## The opposite task: print out all Columns, but rows except fot the first and the last

In [43]:
arr83[-1:0:-1, ::]

array([[21, 22, 23, 24],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [44]:
arr83[1:3, ::]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr83[1:5, ::]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [47]:
### All columns and all rows except of the first ones and the last one (no border elements!)

In [50]:
arr83[1:5, 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [51]:
arr83

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

### Diagonal Elements of 2D array

In [58]:
## The main diagonal and the counter diagonal (second diagonal)

In [53]:
square = np.arange(1, 65).reshape(8, 8)

In [54]:
square

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [55]:
## This is a square matrix, i.e. two dimensions are equal

In [56]:
## here we will need to use loops...

In [57]:
#array[i, j]

In [62]:
for i in range(0, 8):
    diag = square[i, i]
    print(diag)

1
10
19
28
37
46
55
64


In [63]:
for i in range(0, 8):
    print(square[i, i])
   

1
10
19
28
37
46
55
64


In [64]:
## For the main diagonal elements both indices are the same, i==j

In [65]:
## Now the counter diagonal

In [66]:
square

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [67]:
# 8, 15, 22, 29, 36, 43, 50, 57

In [68]:
## Find the common rule for these elemnts

In [69]:
# 8[0,7], 15[1, 6], 22[2, 5], 29[3, 4], 36[4, 3], 43[5, 2], 50[6, 1], 57[7, 0]
#### RULE: i+j = 7 (number of rows or colums minus 1)

In [70]:
### Homework: write code to output the counter diagonal elements.
### Use one (only one!) loop!